on:
  push:
    tags:
      - 'v*'
name: release
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Release
        uses: goreleaser/goreleaser-action@master
        with:
          args: release
          key: ${{ secrets.RELEASE_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}