on:
  push:
    tags:
      - 'v*'
name: release
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Release
        uses: gavincabbage/ghaction-goreleaser@gc/signing
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}