on:
  push:
    tags:
      - 'v*'
name: release
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Import private key
        run: echo "${{ secrets.RELEASE_PRIVATE_KEY }}" | GPG_TTY=$(tty) gpg --import --batch
      - name: Release
        uses: docker://goreleaser/goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release
        if: success()